pipeline:
  build:
    image: python:3.8-bullseye
    commands:
      - apt-get update
      - apt-get install -y git ca-certificates gettext wget python3-pip
      - wget https://gitlab.torproject.org/tpo/tpa/ci-templates/-/raw/main/lektor-requirements.txt -O requirements.txt
      - python3 -m pip install --require-hashes -r requirements.txt
      - lektor build --output-path public
  check_l10n_freshness:
    image: plugins/discord
    secrets:
      - source: webhook_id
        target: plugin_webhook_id
      - source: webhook_token
        target: plugin_webhook_token
    settings:
      message: "Test from woodpecker"
  publish:
    image: debian
    commands:
      - cp -r public/* /var/www/queerscriptors/
    volumes:
      - /var/www/queerscriptors:/var/www/queerscriptors
