pipeline:
  build:
    image: python:3.8-bullseye
    commands:
      - echo Etc/UTC > /etc/timezone
      - export LC_ALL=C.UTF-8
      - export DEBIAN_FRONTEND=noninteractive
      - export APT_CACHE_DIR="$(pwd)/.cache/apt"
      - rm -f /etc/apt/apt.conf.d/docker-clean
      - mkdir -p "${APT_CACHE_DIR}/archives"
      - mkdir -p "${APT_CACHE_DIR}/lists"
      - ./.aptconf
      - apt-get update -qq
      - apt-get upgrade -qy
      - apt-get install -y git gettext ca-certificates wget python3-pip
      - wget https://gitlab.torproject.org/tpo/tpa/ci-templates/-/raw/main/lektor-requirements.txt -O requirements.txt
      - python3 -m pip install --require-hashes -r requirements.txt
      - rm -rf i18n
        #- git clone https://lab.encryptionin.space/Queerscriptors/weblate-website.git i18n
      - lektor build --output-path public
      - lektor build --output-path public
      - lektor build --output-path public
  publish:
    image: debian
    commands:
      - rm -r /var/www/queerscriptors/*
      - cp -r public/* /var/www/queerscriptors/
      - cp -r i18n/ /var/www/queerscriptors/
    volumes:
      - /var/www/queerscriptors:/var/www/queerscriptors 
  check_l10n_freshness:
    image: debian:bullseye
    commands:
      - apt-get update
      - apt-get install gettext git python3-dev python3-setuptools i18nspector python3-polib python3-requests ca-certificates apt-utils -y
      - git clone https://lab.encryptionin.space/Queerscriptors/l10n.git
      - echo 'lets see if there are any updates in the strings for translation'
      - l10n/check_po_status.py main 
