pipeline:
  build:
    image: python:3.8-bullseye
    commands:
      - apt-get update
      - apt-get install -y git gettext python3-pip python3-venv python3-babel
      - virtualenv venv
      - . venv/bin/activate
      - pip install Lektor
      - rm -rf i18n
      - git clone https://lab.encryptionin.space/Queerscriptors/weblate-website.git i18n
      - lektor plugin reinstall
      - lektor build --output-path public
      - lektor build --output-path public
      - lektor build --output-path public
  publish:
    image: debian
    commands:
      - cp -r public/* /var/www/queerscriptors/
    volumes:
      - /var/www/queerscriptors:/var/www/queerscriptors 
  check_l10n_freshness:
    image: debian:bullseye
    commands:
      - apt-get update
      - apt-get install gettext git python3-dev python3-setuptools i18nspector python3-polib python3-requests ca-certificates apt-utils -y
      - git clone https://lab.encryptionin.space/Queerscriptors/l10n.git
      - echo 'lets see if there are any updates in the strings for translation'
      - l10n/check_po_status.py main 
