pipeline:
  build:
    image: python:3.8-bullseye
    commands:
      - apt-get update
      - apt-get install -y git ca-certificates gettext wget python3-pip
      - wget https://gitlab.torproject.org/tpo/tpa/ci-templates/-/raw/main/lektor-requirements.txt -O requirements.txt
      - python3 -m pip install --require-hashes -r requirements.txt
      - lektor build --output-path public
  check_l10n_freshness:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: "Test"
  publish:
    image: debian
    commands:
      - cp -r public/* /var/www/queerscriptors/
    volumes:
      - /var/www/queerscriptors:/var/www/queerscriptors
