pipeline:
  build:
    image: debian
    commands:
      - apt-get install -y python3-venv python3-pip
      - python3 -m pip install --user pipx
      - python3 -m pipx ensurepath
      - pipx install lektor
      - lektor build --output-path public
      - cp -r public/ /var/www/queerscriptors/
    volumes:
      - /var/www/queerscriptors:/var/www/queerscriptors
