steps:
  prepare-dev:
    image: debian
    commands:
      - sed -i -r -e 's/queerscriptors\.org/dev\.queerscriptors\.org/g' website.lektorproject
    when:
      branch: dev
  build:
    image: containers.torproject.org/tpo/web/container-images/lektor:3.3.12
    entrypoint: [ "/bin/sh", "-c", "echo $CI_SCRIPT | base64 -d | /bin/bash -e" ]
    commands:
      - rm -rf i18n
      - git clone https://git.encryptionin.space/Queerscriptors/weblate-website.git i18n
      - lektor build --output-path public -f scss
      - rm -r public
      - lektor build --output-path public -f scss
      - lektor build --output-path public -f scss
  publish:
    image: debian
    commands:
      - rm -r /var/www/queer/main/*
      - cp -r public/* /var/www/queer/main/
      - cp -r i18n/ /var/www/queer/main/i18n/
    volumes:
      - /var/www/queer/main/:/var/www/queer/main/ 
    when:
      branch: main
  publish-dev:
    image: debian
    commands:
      - rm -r /var/www/queer/dev/*
      - cp -r public/* /var/www/queer/dev/
      - cp -r i18n/ /var/www/queer/dev/i18n/
    volumes:
      - /var/www/queer/dev/:/var/www/queer/dev/
    when:
      branch: dev
