pipeline:
  prepare-dev:
    image: debian
    commands:
      - sed -i -r -e 's/queerscriptors\.org/dev\.queerscriptors\.org/g' website.lektorproject
    when:
      branch: dev
  build:
    image: python:3.8-bullseye
    commands:
      - apt-get update
      - apt-get install -y git gettext ca-certificates wget python3-pip
      - wget https://gitlab.torproject.org/tpo/web/lego/-/raw/main/lektor-requirements.txt -O requirements.txt
      - python3 -m pip install --require-hashes -r requirements.txt
      - rm -rf i18n
      - git clone https://lab.encryptionin.space/Queerscriptors/weblate-website.git i18n
      - lektor build --output-path public -f scss
      - rm -r public
      - lektor build --output-path public -f scss
      - lektor build --output-path public -f scss
  publish:
    image: debian
    commands:
      - rm -r /var/www/queer/main*
      - cp -r public/* /var/www/queer/main
      - cp -r i18n/ /var/www/queer/i18n/
    volumes:
      - /var/www/queer/main:/var/www/queer/main 
    when:
      branch: main
  publish-dev:
    image: debian
    commands:
      - rm -r /var/www/queer/dev/*
      - cp -r public/* /var/www/queer/dev/
      - cp -r i18n/ /var/www/queer/dev/i18n/
    volumes:
      - /var/www/queer/dev/:/var/www/queer/dev/
    when:
      branch:
        exclude: main

  #check_l10n_freshness:
  #  image: debian:bullseye
  #  commands:
  #    - apt-get update
  #    - apt-get install gettext git python3-dev python3-setuptools i18nspector python3-polib python3-requests ca-certificates apt-utils -y
  #    - git clone https://lab.encryptionin.space/Queerscriptors/l10n.git
  #    - echo 'lets see if there are any updates in the strings for translation'
  #    - l10n/check_po_status.py main 
