pipeline:
  build:
    image: debian
    commands:
      - apt-get update
      - apt-get install -y python3-venv python3-pip
      - pip install lektor
      - lektor build --output-path public
      - cp -r public/ /var/www/queerscriptors/
    volumes:
      - /var/www/queerscriptors:/var/www/queerscriptors
