steps:
  prepare-dev:
    image: debian
    commands:
      - sed -i -r -e 's/queerscriptors\.org/dev\.queerscriptors\.org/g' website.lektorproject
    when:
      branch: dev
  build:
    image: containers.torproject.org/tpo/tpa/base-images/python:bookworm
    entrypoint: [ "/bin/sh", "-c", "echo $CI_SCRIPT | base64 -d | /bin/bash -e" ]
    commands:
      - apt-get update
      - apt-get install -y git gettext ca-certificates wget python3-polib
      - wget https://gitlab.torproject.org/tpo/web/lego/-/raw/main/lektor-requirements.txt -O requirements.txt
      - python3 -m venv venv
      - source venv/bin/activate 
      - pip install --require-hashes -r requirements.txt
      - rm -rf i18n
      - git clone https://lab.encryptionin.space/Queerscriptors/weblate-website.git i18n
      - lektor build --output-path public -f scss
      - rm -r public
      - lektor build --output-path public -f scss
      - lektor build --output-path public -f scss
  publish:
    image: debian
    commands:
      - rm -r /var/www/queer/main/*
      - cp -r public/* /var/www/queer/main/
      - cp -r i18n/ /var/www/queer/main/i18n/
    volumes:
      - /var/www/queer/main/:/var/www/queer/main/ 
    when:
      branch: main
  publish-dev:
    image: debian
    commands:
      - rm -r /var/www/queer/dev/*
      - cp -r public/* /var/www/queer/dev/
      - cp -r i18n/ /var/www/queer/dev/i18n/
    volumes:
      - /var/www/queer/dev/:/var/www/queer/dev/
    when:
      branch: dev
