pipeline:
  build:
    image: python:3.8-bullseye
    commands:
      - apt-get update
      - apt-get install -y git ca-certificates gettext wget python3-pip python3-babel
      - wget https://gitlab.torproject.org/tpo/tpa/ci-templates/-/raw/main/lektor-requirements.txt -O requirements.txt
      - python3 -m pip install --require-hashes -r requirements.txt
      - lektor build --output-path public
  publish:
    image: debian
    commands:
      - cp -r public/* /var/www/queerscriptors/
    volumes:
      - /var/www/queerscriptors:/var/www/queerscriptors 
  check_l10n_freshness:
    image: python:3.8-bullseye
    commands:
      - apt-get install gettext git python3-dev python3-setuptools i18nspector python3-polib python3-requests ca-certificates apt-utils -y
      - git clone https://lab.encryptionin.space/Queerscriptors/l10n.git
      - echo 'lets see if there are any updates in the strings for translation'
      - l10n/bin/check_po_status.py main
  send_discord_message:
    image: appleboy/drone-discord
    settings:
      webhook_id:
        from_secret: discord_id
      webhook_token:
        from_secret: discord_token
      message: "The lektor build has different pot than weblate-website"
    when:
      - status: [ failure ]
